# Generated by Django 3.2.23 on 2023-12-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_maintopic_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintopic',
            options={'ordering': ['position']},
        ),
    ]
