# Generated by Django 3.2.23 on 2023-12-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_maintopic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(default='Friendly name here', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='description',
        ),
        migrations.AddField(
            model_name='maintopic',
            name='friendly_name',
            field=models.CharField(default='Friendly name here', max_length=100),
        ),
        migrations.CreateModel(
            name='AspectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_content_item', models.TextField()),
                ('aspect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.aspect')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.maintopic')),
            ],
        ),
    ]
