# Generated by Django 3.2.23 on 2023-12-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20231206_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintopic',
            options={},
        ),
    ]
