# Generated by Django 3.2.23 on 2023-12-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_maintopic_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspect',
            old_name='name',
            new_name='programmatic_name',
        ),
        migrations.RenameField(
            model_name='maintopic',
            old_name='name',
            new_name='programmatic_name',
        ),
    ]
