# Generated by Django 3.2.23 on 2023-12-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20231206_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='Keyword here', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('situation', models.TextField()),
                ('question', models.TextField()),
                ('aspect', models.ForeignKey(default='vignette', editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.aspect')),
                ('keywords', models.ManyToManyField(to='dashboard.Keyword')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.maintopic')),
            ],
            options={
                'ordering': ['topic__position'],
            },
        ),
        migrations.DeleteModel(
            name='AspectContent',
        ),
    ]
