# Generated by Django 3.2.23 on 2023-12-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20231212_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vignette',
            name='aspect',
            field=models.ForeignKey(default='vignette', on_delete=django.db.models.deletion.CASCADE, to='dashboard.aspect'),
        ),
    ]
