# Generated by Django 3.2.23 on 2023-12-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_vignette_aspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.maintopic'),
        ),
    ]
